#!/bin/sh
#
# Regenerate the small voxel volumes the check drivers use.
#
# Resolutions are chosen to clear the solver's minimum of 4 voxels per cell per
# direction on every grid the drivers build, including the coarsest one the
# refinement check uses.
#
# Usage: tests/make-geom.sh

set -eu

ROOT=$(cd "$(dirname "$0")/.." && pwd)
OUT="$ROOT/tests/geom"
GEN="$ROOT/tools/genvox.py"

mkdir -p "$OUT"

# A sphere of radius 1 centred in a 4 x 4 x 4 domain. 128^3 gives at least 5.3
# voxels per cell on the 24^3 grid the checks use and 16 on the 8^3 grid the
# refinement check uses.
"$GEN" sphere --out "$OUT/sphere.vox" --size 128 128 128 \
    --domain 4 4 4 --center 2 2 2 --radius 1

# Obstacle-free, for checking that a volume with nothing in it reproduces the
# obstacle-free result exactly.
"$GEN" blank --out "$OUT/empty.vox" --size 128 128 128 --domain 4 4 4

# A hollow box: the cavity is a fluid region sealed off from the rest, which the
# connectivity check has to refuse. genvox.py makes solid bodies, so this one is
# written directly.
python3 - "$OUT/pocket.vox" <<'PYEOF'
import sys

n = 128
path = sys.argv[1]

with open(path, "wb") as f:
    f.write(b"P5V\n")
    f.write(b"# a hollow box: the cavity is a sealed fluid pocket\n")
    f.write(b"# generated by tests/make-geom.sh\n")
    f.write(f"{n} {n} {n}\n255\n".encode())

    for z in range(n):
        plane = bytearray(n * n)
        for y in range(n):
            for x in range(n):
                shell = all(40 <= c < 88 for c in (x, y, z))
                hole = all(52 <= c < 76 for c in (x, y, z))
                plane[y * n + x] = 0 if (shell and not hole) else 255
        f.write(plane)
PYEOF

# An aspect ratio that disagrees with the domain the setups use, so that the
# warning path is exercised. Not an error: the run continues.
"$GEN" blank --out "$OUT/skewed.vox" --size 256 64 64 --domain 4 4 4

ls -l "$OUT"
