#!/bin/sh
#
# Regenerate the small voxel volumes the check drivers use.
#
# Resolutions are chosen to clear the solver's minimum of 4 voxels per cell per
# direction on every grid the drivers build, including the coarsest one the
# refinement check uses.
#
# Usage: tests/make-geom.sh

set -eu

ROOT=$(cd "$(dirname "$0")/.." && pwd)
OUT="$ROOT/tests/geom"
GEN="$ROOT/tools/genvox.py"

mkdir -p "$OUT"

# A sphere of radius 1 centred in a 4 x 4 x 4 domain. 128^3 gives at least 5.3
# voxels per cell on the 24^3 grid the checks use and 16 on the 8^3 grid the
# refinement check uses.
"$GEN" sphere --out "$OUT/sphere.vox" --size 128 128 128 \
    --domain 4 4 4 --center 2 2 2 --radius 1

# Obstacle-free, for checking that a volume with nothing in it reproduces the
# obstacle-free result exactly.
"$GEN" blank --out "$OUT/empty.vox" --size 128 128 128 --domain 4 4 4

# A hollow box: the cavity is a fluid region sealed off from the rest, which the
# connectivity check has to refuse. genvox.py makes solid bodies, so this one is
# written directly.
python3 - "$OUT/pocket.vox" <<'PYEOF'
import sys

n = 128
path = sys.argv[1]

with open(path, "wb") as f:
    f.write(b"P5V\n")
    f.write(b"# a hollow box: the cavity is a sealed fluid pocket\n")
    f.write(b"# generated by tests/make-geom.sh\n")
    f.write(f"{n} {n} {n}\n255\n".encode())

    for z in range(n):
        plane = bytearray(n * n)
        for y in range(n):
            for x in range(n):
                shell = all(40 <= c < 88 for c in (x, y, z))
                hole = all(52 <= c < 76 for c in (x, y, z))
                plane[y * n + x] = 0 if (shell and not hole) else 255
        f.write(plane)
PYEOF

# A known pattern for the round-trip check: solid for x below the midpoint of a
# unit domain, so a voxel's expected value follows from its index alone.
"$GEN" box --out "$OUT/probe.vox" --size 32 32 32 \
    --domain 1 1 1 --corner 0 0 0 --extent 0.5 1 1

# The same content with a deliberately awkward header: comments between the
# fields, runs of blank lines, and tabs. The reader has to cope with all of it.
python3 - "$OUT/odd-header.vox" <<'PYEOF'
import sys

n = 32
with open(sys.argv[1], "wb") as f:
    f.write(b"P5V\n")
    f.write(b"# a header that exercises the parser\n")
    f.write(b"\n\n")
    f.write(b"\t32   \n")
    f.write(b"# the voxel counts are split across lines on purpose\n")
    f.write(b"32\n\t\t32\n")
    f.write(b"# and the maximum value has its own comment\n")
    f.write(b"255\n")

    for z in range(n):
        plane = bytearray(n * n)
        for y in range(n):
            for x in range(n):
                plane[y * n + x] = 0 if x < n // 2 else 255
        f.write(plane)
PYEOF

# Two bodies of comparable solid volume and very different surface area, for the
# claim that the interior sweep does not care how complicated the geometry is.
# The lattice is 125 small cubes with the same total volume as a sphere of
# radius 1, and about six times its surface.
python3 - "$OUT/lattice.vox" <<'PYEOF'
import sys

n = 192            # 48 cells across a 4-unit domain needs 4 voxels per cell
domain = 4.0
side = 0.3236      # 125 * side^3 == 4/3 * pi, the volume of the unit sphere
half = side / 2

centres = [0.4 + 0.8 * i for i in range(5)]

with open(sys.argv[1], "wb") as f:
    f.write(b"P5V\n")
    f.write(b"# 125 cubes with the volume of a unit sphere and six times its surface\n")
    f.write(b"# generated by tests/make-geom.sh\n")
    f.write(f"{n} {n} {n}\n255\n".encode())

    def hit(v):
        return any(abs(v - c) <= half for c in centres)

    for vz in range(n):
        z = (vz + 0.5) / n * domain
        hz = hit(z)
        plane = bytearray(b"\xff" * (n * n))
        if hz:
            for vy in range(n):
                y = (vy + 0.5) / n * domain
                if not hit(y):
                    continue
                row = vy * n
                for vx in range(n):
                    x = (vx + 0.5) / n * domain
                    if hit(x):
                        plane[row + vx] = 0
        f.write(plane)
PYEOF

# An aspect ratio that disagrees with the domain the setups use, so that the
# warning path is exercised. Not an error: the run continues.
"$GEN" blank --out "$OUT/skewed.vox" --size 256 64 64 --domain 4 4 4

ls -l "$OUT"
