#!/usr/bin/env python3
"""
Rasterize an obstacle to a P5V voxel volume for use as `geometryFile`.

The format is the three-dimensional counterpart of the binary PGM the 2D solver
reads: an ASCII header, then one byte per voxel with x varying fastest, then y,
then z. A voxel below 128 is solid. No axis is flipped -- index order matches
axis order and the origin is the domain origin, the same direction the grid is
indexed.

Usage examples:

    tools/genvox.py cylinder --out geometry/karman.vox --size 800 320 320 \
        --domain 20 8 8 --axis z --center 5 4 --radius 1
    tools/genvox.py sphere   --out geometry/sphere.vox --size 256 256 256 \
        --domain 4 4 4 --center 2 2 2 --radius 0.5
    tools/genvox.py box      --out geometry/backstep.vox --size 560 120 120 \
        --domain 7 1.5 1.5 --corner 0 0 0 --extent 1 0.5 1.5
    tools/genvox.py blank    --out geometry/empty.vox --size 64 64 64
"""
import argparse
import sys


def write_header(fp, nx, ny, nz, comment=None):
    fp.write(b"P5V\n")
    if comment:
        for line in comment.splitlines():
            fp.write(b"# " + line.encode() + b"\n")
    fp.write(f"{nx} {ny} {nz}\n255\n".encode())


def generate(path, nx, ny, nz, domain, solid, comment=None):
    """solid(x, y, z) -> bool, with x, y, z the voxel centre in physical units."""
    xlength, ylength, zlength = domain

    with open(path, "wb") as fp:
        write_header(fp, nx, ny, nz, comment)

        # One plane at a time, so that a large volume never has to be held whole.
        for vz in range(nz):
            z = (vz + 0.5) / nz * zlength
            plane = bytearray(nx * ny)
            idx = 0
            for vy in range(ny):
                y = (vy + 0.5) / ny * ylength
                for vx in range(nx):
                    x = (vx + 0.5) / nx * xlength
                    plane[idx] = 0 if solid(x, y, z) else 255
                    idx += 1
            fp.write(plane)


def main(argv=None):
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("shape", choices=["sphere", "cylinder", "box", "blank"])
    ap.add_argument("--out", required=True)
    ap.add_argument("--size", nargs=3, type=int, required=True, metavar=("NX", "NY", "NZ"))
    ap.add_argument(
        "--domain",
        nargs=3,
        type=float,
        default=[1.0, 1.0, 1.0],
        metavar=("XLENGTH", "YLENGTH", "ZLENGTH"),
    )
    ap.add_argument("--center", nargs="+", type=float)
    ap.add_argument("--radius", type=float)
    ap.add_argument("--axis", choices=["x", "y", "z"], default="z")
    ap.add_argument("--corner", nargs=3, type=float, metavar=("X0", "Y0", "Z0"))
    ap.add_argument("--extent", nargs=3, type=float, metavar=("XLEN", "YLEN", "ZLEN"))
    args = ap.parse_args(argv)

    nx, ny, nz = args.size

    if args.shape == "blank":
        solid = lambda x, y, z: False
        comment = "blank"

    elif args.shape == "sphere":
        if args.center is None or len(args.center) != 3 or args.radius is None:
            ap.error("sphere needs --center XC YC ZC and --radius")
        xc, yc, zc = args.center
        r2 = args.radius ** 2
        solid = lambda x, y, z: (x - xc) ** 2 + (y - yc) ** 2 + (z - zc) ** 2 <= r2
        comment = f"sphere at ({xc}, {yc}, {zc}) radius {args.radius}"

    elif args.shape == "cylinder":
        if args.center is None or len(args.center) != 2 or args.radius is None:
            ap.error("cylinder needs --center C1 C2 (the two axes it is not along) "
                     "and --radius")
        c1, c2 = args.center
        r2 = args.radius ** 2
        if args.axis == "x":
            solid = lambda x, y, z: (y - c1) ** 2 + (z - c2) ** 2 <= r2
        elif args.axis == "y":
            solid = lambda x, y, z: (x - c1) ** 2 + (z - c2) ** 2 <= r2
        else:
            solid = lambda x, y, z: (x - c1) ** 2 + (y - c2) ** 2 <= r2
        comment = (f"cylinder along {args.axis} at ({c1}, {c2}) "
                   f"radius {args.radius}")

    else:
        if args.corner is None or args.extent is None:
            ap.error("box needs --corner X0 Y0 Z0 and --extent XLEN YLEN ZLEN")
        x0, y0, z0 = args.corner
        lx, ly, lz = args.extent
        solid = lambda x, y, z: (
            x0 <= x <= x0 + lx and y0 <= y <= y0 + ly and z0 <= z <= z0 + lz
        )
        comment = f"box at ({x0}, {y0}, {z0}) extent ({lx}, {ly}, {lz})"

    comment = (f"{comment}\ndomain {args.domain[0]} x {args.domain[1]} x "
               f"{args.domain[2]}\ngenerated by tools/genvox.py")

    generate(args.out, nx, ny, nz, args.domain, solid, comment)
    print(f"wrote {args.out}: {nx} x {ny} x {nz} voxels, "
          f"{nx * ny * nz} bytes of data")
    return 0


if __name__ == "__main__":
    sys.exit(main())
